analyzers: ["mypy_analyzer_v1", "signature_analyzer_v1", "hallucination_analyzer_v1"]
model_first: "ft:gpt-3.5-turbo-1106:personal::8LCi9Q0d"
model_feedback: "ft:gpt-3.5-turbo-1106:personal::8LCi9Q0d"
feedback_variant: "coworker"
system_prompt: 2023-11-15_GPT-Builder.txt
dataset: "LLMcoder-Eval/level_2"
max_iter: 5
log_conversation: true
scores: [
  "extrinsic.levenshtein_distance_score",
  "extrinsic.bleu_score",
  "extrinsic.trf_similarity_score",
  "extrinsic.sequence_matcher_score",
  "extrinsic.gpt_reviewer_score",
  "intrinsic.loops_required_score",
  "intrinsic.tokens_used_score",
  "intrinsic.agility_score",
  "intrinsic.time_score",
  "intrinsic.all_analyzers_passed_score",
  "intrinsic.total_tokens_generated_score"
]
n_choices: 1
n_procs: 1
